<a href="https://colab.research.google.com/github/ShvetsAlla/repo1/blob/main/NumPy_pip_install_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
# бібліотека NumPy - це основна бібліотека для наукових обчислень у Python.

# Об'єкт ndarray в NumPy -  це  ключовий об'єкт у бібліотеці NumPy.
# ndarray є скороченням від "n-dimensional array", що означає "багатовимірний масив".
# Це основний тип даних, який використовується в NumPy для зберігання і обробки багатовимірних масивів.
# ndarray не є вбудованим типом даних у Python, як, наприклад, int, float, або list.
# Натомість, ndarray є типом, який надається бібліотекою NumPy, спеціалізованою бібліотекою для наукових обчислень у Python.

# np.array - це функція в NumPy, яка використовується для створення нових об'єктів ndarray.
# Коли ви створюєте масив за допомогою np.array, ви отримуєте екземпляр ndarray.

In [3]:
import numpy as np # стандартний еліас для numpy - np
# create a 1D array from a list
a = np.array([1, 2, 3, 4, 5], dtype=float)

print(a)  # [1. 2. 3. 4. 5.]
a+5

[1. 2. 3. 4. 5.]


array([ 6.,  7.,  8.,  9., 10.])

In [4]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [5]:
# create a 2d array
m = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)

print(m)

[[1 2 3]
 [4 5 6]]


In [7]:
a = np.array([1, 2, 3, 4, 5], dtype=float)
m = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)

# Розмірність створеного вектора та матриці можна подивитися за допомогою атрибуту shape.Розмірність - це кортеж, який містить кількість елементів у кожному розмірі масиву.
print(a.shape)  # (5,)
print(m.shape)  # (2, 3)

# size - це атрибут, який містить загальну кількість елементів у масиві.
print(a.size)
print(m.size)

# dtype - це атрибут, який містить тип даних, який зберігається в масиві.
print(a.dtype)
print(m.dtype)

(5,)
(2, 3)
5
6
float64
int64


In [9]:
# Щоб створити масив з випадковими числами, використовуйте функцію random.
import numpy as np

a = np.random.random(3) # 3 випадкових числа від 0 до 1
b = np.random.random((3, 3)) # 3 випадкових числа від 0 до 1
print(a , '\n')
print(b)

[0.17948663 0.04626227 0.9656983 ] 

[[0.22337867 0.55415139 0.80802829]
 [0.26068288 0.74709374 0.67411242]
 [0.07588755 0.94774924 0.10784789]]


In [10]:
# Щоб створити масив з одиниць, використовуйте функцію ones.
import numpy as np

a = np.ones((5,), dtype=float)
print(a)

m = np.ones((2, 3), dtype=int)
print(m)

[1. 1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]]


In [11]:
# Щоб створити масив з нулів, використовуйте функцію zeros.
import numpy as np

a = np.zeros(5, dtype=float)
print(a)

m = np.zeros((2, 3), dtype=int)
print(m)

[0. 0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]]


In [12]:
# Щоб створити одиничну матрицю, використовуйте функцію eye.
m = np.identity(4, dtype=int)
print(m)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [13]:
# Щоб створити масив з послідовністю чисел, використовуйте функцію arange.
import numpy as np

a = np.arange(5) # 5 послідовних чисел починаючи з 0
b = np.arange(1, 3, 0.5) # послідовність чисел від 1 до 3 з кроком 0.5
print(a)
print(b)

[0 1 2 3 4]
[1.  1.5 2.  2.5]


In [14]:
# Щоб створити масив з рівномірно розподіленими числами, використовуйте функцію linspace.
# Ця функція приймає три аргументи: початок послідовності, кінець послідовності, кількість елементів.
# По замовчуванню кількість елементів дорівнює 50.
import numpy as np

a = np.linspace(1, 5, num=5) # 5 рівномірно розподілених чисел від 1 до 5
b = np.linspace(1, 3, num=3) # 3 рівномірно розподілених чисел від 1 до 3
print(a)
print(b)

[1. 2. 3. 4. 5.]
[1. 2. 3.]


In [15]:
# Масив NumPy можна розділити на частини та присвоїти їм індекси. Принцип роботи схожий на те, як це відбувається зі списками Python.

import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a[0]) # перший елемент
print(a[1:]) # з другого елемента до кінця
print(a[:2]) # з початку до другого елемента

1
[2 3 4 5]
[1 2]


In [16]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a[0])     # перший рядок
print(a[0][0:2])  # перший рядок, перші два елементи
print(a[0][0])  # перший рядок, перший елемент
print('\n')
print(a[1, 1]) # другий рядок, другий елемент
print(a[1:, 1]) # з другого рядка, другий елемент
print(a[0, :2]) # перший рядок, перші два елементи

[1 2 3]
[1 2]
1


5
[5 8]
[1 2]


In [17]:
# за індексом можна задати елемент масива
print(a)
a[0, 0] = 10
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]
